image: Visual Studio 2017

skip_branch_with_pr: true

build_script:
  - cmd: nuget restore "source\RSS Bandit.sln"
  - cmd: msbuild MSBuildDefault.proj /t:Daily /p:Configuration=Release  

test: off

artifacts:
  - path: '**\*.zip'
